version: '2'

services:
  inventory:
    image: 'inventory:latest'
    depends_on:
      - inventory-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://inventory-db:5432/inventory
      - SPRING_DATASOURCE_USERNAME=inventory
      - SPRING_DATASOURCE_PASSWORD=inventory
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080

  production-log:
    image: 'production-log:latest'
    depends_on:
      - production-log-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://production-log-db:5432/production_log
      - SPRING_DATASOURCE_USERNAME=production_log
      - SPRING_DATASOURCE_PASSWORD=production_log
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8081:8080

  consumption-log:
    image: 'consumption-log:latest'
    depends_on:
      - consumption-log-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://consumption-log-db:5432/consumption_log
      - SPRING_DATASOURCE_USERNAME=consumption_log
      - SPRING_DATASOURCE_PASSWORD=consumption_log
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8082:8080

  invoice:
    image: 'invoice:latest'
    ports:
      - 8083:8080

  inventory-db:
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_USER=inventory
      - POSTGRES_PASSWORD=inventory
    volumes:
      - ./data:/var/lib/postgresql

  consumption-log-db:
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_USER=consumption_log
      - POSTGRES_PASSWORD=consumption_log
    volumes:
      - ./data:/var/lib/postgresql

  production-log-db:
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_USER=production_log
      - POSTGRES_PASSWORD=production_log
    volumes:
      - ./data:/var/lib/postgresql